export WEZTERM_RUNTIME_LOG_ENABLED=1
export WEZTERM_RUNTIME_LOG_LEVEL=info
export WEZTERM_RUNTIME_LOG_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/wezterm-runtime/logs/runtime.log"
export WEZTERM_RUNTIME_LOG_ROTATE_BYTES=5242880
export WEZTERM_RUNTIME_LOG_ROTATE_COUNT=5
export WEZTERM_RUNTIME_LOG_CATEGORIES=""
